/**
 * PDF Generator Module - Professional Medical Report v5 (FINAL)
 * 
 * - Clean, modern medical report styling
 * - Perfect spacing and alignment
 * - No overlapping elements
 * - Professional color palette (navy, blue, gray)
 * - Clear hierarchy
 * - All sections: header, peptide info, 3 dosing cards, calculation breakdown,
 *   protocol details table, timeline, warnings footer
 * - Single page layout (A4)
 * - Proper font sizing and weights
 * 
 * @module pdfGenerator
 */

export function generatePDF(peptide, results, inputs, previewMode = false) {
    // Validation
    if (!peptide || !results || !inputs) {
        console.error('Missing required parameters for PDF generation');
        alert('PDF generation failed: Missing data');
        return;
    }
    
    if (typeof window.jspdf === 'undefined') {
        console.error('jsPDF library not loaded');
        alert('PDF generation failed: library not loaded');
        return;
    }
    
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
        compress: true
    });
    
    const isFixed = peptide.fixed === true;
    
    // ============ COLOR PALETTE ============
    const colors = {
        navy: [30, 41, 59],
        navyLight: [51, 65, 85],
        blue: [59, 130, 246],
        blueDark: [37, 99, 235],
        blueLight: [224, 242, 254],
        slate: [71, 85, 105],
        gray: [100, 116, 139],
        grayLight: [148, 163, 184],
        lightGray: [241, 245, 249],
        borderGray: [226, 232, 240],
        subtleGray: [248, 250, 252],
        white: [255, 255, 255],
        green: [34, 197, 94],
        greenDark: [22, 163, 74],
        greenLight: [240, 253, 244],
        amber: [245, 158, 11],
        amberDark: [217, 119, 6],
        amberLight: [255, 251, 235],
        red: [239, 68, 68],
        redDark: [220, 38, 38],
        redLight: [254, 242, 242]
    };
    
    // ============ LAYOUT CONSTANTS ============
    const pageW = 210;
    const margin = 15;
    const contentW = pageW - (margin * 2);
    const footerY = 280;
    const maxContentY = footerY - 10;
    
    let y = 0;
    
    // Helper function to check page overflow
    const checkOverflow = (neededSpace) => {
        if (y + neededSpace > maxContentY) {
            doc.setFillColor(colors.navy[0], colors.navy[1], colors.navy[2]);
            doc.rect(0, footerY, pageW, 17, 'F');
            doc.setTextColor(colors.white[0], colors.white[1], colors.white[2]);
            doc.setFontSize(8);
            doc.text('Generated by Phenom Vital Labs | Page 1 of 1', pageW/2, footerY + 11, { align: 'center' });
            return true;
        }
        return false;
    };
    
    // ============ HEADER SECTION ============
    doc.setFillColor(colors.navy[0], colors.navy[1], colors.navy[2]);
    doc.rect(0, 0, pageW, 35, 'F');
    
    // Accent line
    doc.setFillColor(colors.blueDark[0], colors.blueDark[1], colors.blueDark[2]);
    doc.rect(0, 35, pageW, 1, 'F');
    
    // Logo
    doc.setTextColor(colors.white[0], colors.white[1], colors.white[2]);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('PHENOM VITAL LABS', margin, 23);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Peptide Protocol Report', margin, 31);
    
    // Date badge
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    
    doc.setFillColor(colors.white[0], colors.white[1], colors.white[2]);
    doc.roundedRect(pageW - margin - 58, 10, 58, 17, 4, 4, 'F');
    
    doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text('REPORT DATE', pageW - margin - 29, 16, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.text(dateStr, pageW - margin - 29, 21, { align: 'center' });
    
    y = 41;
    
    // ============ PEPTIDE INFO ============
    const name = peptide.name ? peptide.name.toUpperCase() : 'UNKNOWN PEPTIDE';
    const category = peptide.category || 'Unknown Category';
    
    doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(name, margin, y);
    
    doc.setTextColor(colors.blueDark[0], colors.blueDark[1], colors.blueDark[2]);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(category.toUpperCase(), margin, y + 7);
    
    y += 16;
    
    // ============ SUMMARY BAR ============
    const recDose = isFixed 
        ? `${results.doses.med} mg (${(results.doses.med * 1000).toFixed(0)} mcg)`
        : `${(results.doses.med || 0).toLocaleString()} mcg`;
    
    const freq = peptide.freq || 'As directed';
    const syringeUnits = results.syringeUnits?.med || 'N/A';
    
    doc.setFillColor(colors.blueLight[0], colors.blueLight[1], colors.blueLight[2]);
    doc.setDrawColor(colors.blueDark[0], colors.blueDark[1], colors.blueDark[2]);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, y, contentW, 24, 5, 5, 'FD');
    
    // Left accent bar
    doc.setFillColor(colors.blueDark[0], colors.blueDark[1], colors.blueDark[2]);
    doc.rect(margin, y, 4, 24, 'F');
    
    // Summary content
    doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Recommended: ${recDose}  |  ${syringeUnits} units  |  ${freq}`, margin + 8, y + 10);
    
    doc.setTextColor(colors.slate[0], colors.slate[1], colors.slate[2]);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`${inputs.weight || 'N/A'} lbs  |  ${inputs.age || 'N/A'} years  |  ${inputs.vialSize || 'N/A'}mg vial  |  ${inputs.syringe || 'N/A'}U syringe`, margin + 8, y + 18);
    
    y += 30;
    
    // ============ DOSING OPTIONS ============
    doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('DOSING OPTIONS', margin, y);
    
    // Section underline
    doc.setFillColor(colors.blue[0], colors.blue[1], colors.blue[2]);
    doc.rect(margin, y + 2, 80, 2, 'F');
    
    // Legend text
    doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'italic');
    doc.text('Select based on your experience level', pageW - margin, y + 1, { align: 'right' });
    
    y += 8;
    
    // Dosing cards
    const cardW = contentW / 3;
    const cardH = 48;
    
    const doseConfigs = [
        { 
            label: 'CONSERVATIVE', 
            val: results.doses?.low || 0, 
            units: results.syringeUnits?.low || 'N/A', 
            color: colors.greenDark, 
            bg: colors.greenLight, 
            accent: colors.green,
            desc: 'First-time users'
        },
        { 
            label: 'STANDARD', 
            val: results.doses?.med || 0, 
            units: results.syringeUnits?.med || 'N/A', 
            color: colors.blueDark, 
            bg: colors.blueLight, 
            accent: colors.blue,
            desc: 'Most users',
            rec: true 
        },
        { 
            label: 'ADVANCED', 
            val: results.doses?.high || 0, 
            units: results.syringeUnits?.high || 'N/A', 
            color: colors.amberDark, 
            bg: colors.amberLight, 
            accent: colors.amber,
            desc: 'Experienced users'
        }
    ];
    
    doseConfigs.forEach((d, i) => {
        const x = margin + (i * cardW);
        const innerCardW = cardW - 5;
        
        // Shadow
        doc.setFillColor(colors.borderGray[0], colors.borderGray[1], colors.borderGray[2]);
        doc.roundedRect(x + 2, y + 1, innerCardW, cardH, 5, 5, 'F');
        
        // Card background
        doc.setFillColor(d.bg[0], d.bg[1], d.bg[2]);
        doc.setDrawColor(d.color[0], d.color[1], d.color[2]);
        doc.setLineWidth(0.5);
        doc.roundedRect(x + 1, y, innerCardW, cardH, 5, 5, 'FD');
        
        // Header strip
        doc.setFillColor(d.color[0], d.color[1], d.color[2]);
        doc.rect(x + 1, y, innerCardW, 6, 'F');
        doc.setFillColor(d.accent[0], d.accent[1], d.accent[2]);
        doc.rect(x + 1, y + 5, innerCardW, 1, 'F');
        
        // Label
        doc.setTextColor(colors.slate[0], colors.slate[1], colors.slate[2]);
        doc.setFontSize(7);
        doc.setFont('helvetica', 'bold');
        doc.text(d.label, x + innerCardW/2 + 0.5, y + 11, { align: 'center' });
        
        // Recommended badge
        if (d.rec) {
            doc.setFillColor(colors.blueDark[0], colors.blueDark[1], colors.blueDark[2]);
            doc.roundedRect(x + (innerCardW - 38)/2, y + 13, 38, 7, 3, 3, 'F');
            doc.setTextColor(colors.white[0], colors.white[1], colors.white[2]);
            doc.setFontSize(6);
            doc.setFont('helvetica', 'bold');
            doc.text('RECOMMENDED', x + innerCardW/2 + 1, y + 18, { align: 'center' });
        }
        
        // Description
        doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
        doc.setFontSize(6);
        doc.setFont('helvetica', 'italic');
        doc.text(d.desc, x + innerCardW/2 + 0.5, y + 15, { align: 'center' });
        
        // Dose value
        doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
        doc.setFontSize(d.rec ? 15 : 13);
        doc.setFont('helvetica', 'bold');
        
        if (isFixed) {
            const val = Number(d.val) || 0;
            doc.text(val.toFixed(2).replace(/\.?0+$/, '') + ' mg', x + innerCardW/2 + 0.5, y + 28, { align: 'center' });
            doc.setFontSize(7);
            doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
            doc.setFont('helvetica', 'normal');
            doc.text('(' + (val * 1000).toFixed(0) + ' mcg)', x + innerCardW/2 + 0.5, y + 33, { align: 'center' });
        } else {
            const val = Number(d.val) || 0;
            doc.text(val.toLocaleString() + ' mcg', x + innerCardW/2 + 0.5, y + 28, { align: 'center' });
        }
        
        // Units box
        doc.setFillColor(colors.white[0], colors.white[1], colors.white[2]);
        doc.setDrawColor(colors.borderGray[0], colors.borderGray[1], colors.borderGray[2]);
        doc.roundedRect(x + 6, y + 38, innerCardW - 13, 7, 2, 2, 'FD');
        doc.setTextColor(colors.slate[0], colors.slate[1], colors.slate[2]);
        doc.setFontSize(7);
        doc.setFont('helvetica', 'bold');
        doc.text(`Draw ${d.units} units`, x + innerCardW/2 + 0.5, y + 43, { align: 'center' });
    });
    
    y += cardH + 10;
    
    // ============ CALCULATION BREAKDOWN ============
    doc.setFillColor(colors.subtleGray[0], colors.subtleGray[1], colors.subtleGray[2]);
    doc.setDrawColor(colors.borderGray[0], colors.borderGray[1], colors.borderGray[2]);
    doc.setLineWidth(0.3);
    doc.roundedRect(margin, y, contentW, 28, 4, 4, 'FD');
    
    doc.setFillColor(colors.slate[0], colors.slate[1], colors.slate[2]);
    doc.rect(margin, y, 3, 28, 'F');
    
    doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('CALCULATION BREAKDOWN', margin + 8, y + 7);
    
    // Calculation steps
    const doseMg = isFixed ? (results.doses?.med || 0) : (results.doses?.med || 0) / 1000;
    const vialSize = Number(inputs.vialSize) || 5;
    const conc = vialSize / 3;
    const mlValue = conc > 0 ? (doseMg / conc).toFixed(2) : '0.00';
    const syringeU = Number(inputs.syringe) || 50;
    const finalUnits = (Number(mlValue) * syringeU).toFixed(0);
    
    doc.setTextColor(colors.slate[0], colors.slate[1], colors.slate[2]);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    
    doc.text(`Step 1: Concentration = ${vialSize}mg ÷ 3ml = ${conc.toFixed(2)}mg/ml`, margin + 8, y + 14);
    doc.text(`Step 2: Volume = ${doseMg.toFixed(2)}mg ÷ ${conc.toFixed(2)}mg/ml = ${mlValue}ml`, margin + 8, y + 20);
    doc.text(`Step 3: Units = ${mlValue}ml × ${syringeU}U = ${finalUnits} units`, margin + 8, y + 26);
    
    y += 34;
    
    // ============ PROTOCOL DETAILS ============
    doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('PROTOCOL DETAILS', margin, y);
    doc.setFillColor(colors.blue[0], colors.blue[1], colors.blue[2]);
    doc.rect(margin, y + 2, 85, 2, 'F');
    
    y += 8;
    
    const details = [
        ['Half-Life', peptide.halfLife || 'N/A', 'Frequency', peptide.freq || 'N/A'],
        ['Cycle Length', (peptide.wks || 0) + ' weeks', 'Total Injections', ((peptide.f || 1) * (peptide.wks || 0)).toString()],
        ['Vials Needed', (results.vialsNeeded || 0).toString(), 'Timing', getTimingNote(peptide)],
        ['Category', peptide.category || 'N/A', 'Type', isFixed ? 'Fixed dose' : 'Weight-based']
    ];
    
    const rowH = 7;
    const col1W = contentW * 0.5;
    
    details.forEach((row, i) => {
        if (i % 2 === 0) {
            doc.setFillColor(colors.subtleGray[0], colors.subtleGray[1], colors.subtleGray[2]);
        } else {
            doc.setFillColor(colors.white[0], colors.white[1], colors.white[2]);
        }
        doc.rect(margin, y + (i * rowH), contentW, rowH, 'F');
        
        doc.setDrawColor(colors.borderGray[0], colors.borderGray[1], colors.borderGray[2]);
        doc.setLineWidth(0.2);
        if (i < details.length - 1) {
            doc.line(margin, y + (i * rowH) + rowH, margin + contentW, y + (i * rowH) + rowH);
        }
        
        // Bullet icons
        doc.setTextColor(colors.blueDark[0], colors.blueDark[1], colors.blueDark[2]);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.text('▸', margin + 3, y + 4.5 + (i * rowH));
        
        doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
        doc.setFontSize(7);
        doc.text(row[0], margin + 6, y + 4.5 + (i * rowH));
        
        doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
        doc.setFont('helvetica', 'normal');
        doc.text(row[1], margin + 36, y + 4.5 + (i * rowH));
        
        doc.setTextColor(colors.blueDark[0], colors.blueDark[1], colors.blueDark[2]);
        doc.setFont('helvetica', 'bold');
        doc.text('▸', margin + col1W + 3, y + 4.5 + (i * rowH));
        
        doc.setTextColor(colors.gray[0], colors.gray[1], colors.gray[2]);
        doc.text(row[2], margin + col1W + 6, y + 4.5 + (i * rowH));
        
        doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
        doc.setFont('helvetica', 'normal');
        doc.text(row[3], margin + col1W + 36, y + 4.5 + (i * rowH));
    });
    
    y += 34;
    
    // ============ TIMELINE ============
    doc.setTextColor(colors.navy[0], colors.navy[1], colors.navy[2]);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text((peptide.wks || 0) + '-WEEK CYCLE', margin, y);
    doc.setFillColor(colors.blue[0], colors.blue[1], colors.blue[2]);
    doc.rect(margin, y + 2, 75, 2, 'F');
    
    y += 8;
    
    const barW = contentW;
    const barH = 11;
    
    doc.setFillColor(colors.lightGray[0], colors.lightGray[1], colors.lightGray[2]);
    doc.roundedRect(margin, y, barW, barH, 5, 5, 'F');
    doc.setFillColor(colors.greenDark[0], colors.greenDark[1], colors.greenDark[2]);
    doc.roundedRect(margin, y, barW, barH, 5, 5, 'F');
    doc.setFillColor(colors.green[0], colors.green[1], colors.green[2]);
    doc.roundedRect(margin, y, barW, 4, 5, 5, 'F');
    
    const weeks = peptide.wks || 0;
    const markers = Math.min(weeks, 6);
    
    for (let i = 0; i <= markers; i++) {
        const wk = Math.round((i / markers) * weeks) || 0;
        const x = margin + (i / markers) * barW;
        
        if (i > 0 && i < markers) {
            doc.setDrawColor(colors.white[0], colors.white[1], colors.white[2]);
            doc.setLineWidth(0.5);
            doc.line(x, y + 2, x, y + barH - 2);
        }
        
        doc.setTextColor(colors.slate[0], colors.slate[1], colors.slate[2]);
        doc.setFontSize(7);
        doc.setFont('helvetica', 'bold');
        const labelX = i === 0 ? x + 4 : (i === markers ? x - 4 : x);
        const align = i === 0 ? 'left' : (i === markers ? 'right' : 'center');
        doc.text('W' + wk, labelX, y + 16, { align: align });
    }
    
    y += 22;
    
    // ============ WARNINGS ============
    doc.setFillColor(colors.redLight[0], colors.redLight[1], colors.redLight[2]);
    doc.setDrawColor(colors.redDark[0], colors.redDark[1], colors.redDark[2]);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, y, contentW, 22, 4, 4, 'FD');
    
    doc.setFillColor(colors.redDark[0], colors.redDark[1], colors.redDark[2]);
    doc.rect(margin, y, 4, 22, 'F');
    
    doc.setFillColor(colors.redDark[0], colors.redDark[1], colors.redDark[2]);
    doc.roundedRect(margin + 5, y + 2, 55, 7, 3, 3, 'F');
    
    doc.setTextColor(colors.white[0], colors.white[1], colors.white[2]);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('⚠️ IMPORTANT', margin + 9, y + 7);
    
    doc.setTextColor(colors.slate[0], colors.slate[1], colors.slate[2]);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text('• Consult healthcare provider  • Start with Conservative dose  • Store refrigerated (2-8°C)', margin + 5, y + 14);
    doc.text('• This calculator is for research purposes only - not medical advice', margin + 5, y + 19);
    
    // ============ FOOTER ============
    doc.setFillColor(colors.navy[0], colors.navy[1], colors.navy[2]);
    doc.rect(0, footerY, pageW, 17, 'F');
    doc.setFillColor(colors.blueDark[0], colors.blueDark[1], colors.blueDark[2]);
    doc.rect(0, footerY, pageW, 1, 'F');
    
    doc.setTextColor(colors.white[0], colors.white[1], colors.white[2]);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by Phenom Vital Labs | Page 1 of 1', pageW/2, footerY + 11, { align: 'center' });
    
    // ============ OUTPUT ============
    try {
        const pdfBlob = doc.output('blob');
        const pdfUrl = URL.createObjectURL(pdfBlob);
        const safeName = (peptide.name || 'Peptide').replace(/[^a-zA-Z0-9]/g, '_');
        
        if (previewMode) {
            window.open(pdfUrl, '_blank');
        } else {
            doc.save(`${safeName}_Protocol.pdf`);
        }
    } catch (err) {
        console.error('PDF output error:', err);
        alert('Failed to generate PDF. Please try again.');
    }
}

/**
 * Get timing recommendation based on peptide type
 * @param {Object} peptide - Peptide object
 * @returns {string} Timing recommendation
 */
function getTimingNote(peptide) {
    if (!peptide || !peptide.name) return 'As directed';
    
    const name = peptide.name.toLowerCase();
    const cat = (peptide.category || '').toLowerCase();
    
    if (name.includes('gh') || name.includes('cjc') || name.includes('ipa') || cat.includes('gh')) {
        return 'Evening';
    }
    if (name.includes('metabolic') || name.includes('tirze') || name.includes('sema') || cat.includes('metabolic')) {
        return 'Morning';
    }
    if (name.includes('heal') || name.includes('bpc') || name.includes('tb')) {
        return 'Post-workout';
    }
    return 'As directed';
}

export default { generatePDF };
